name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Make scripts executable
        run: |
          chmod +x ./ci/ci-compile.sh

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install platformio
        run: |
          pip install platformio==6.1.4

      - name: build examples
        run: ./ci/ci-compile.sh

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
          chmod +x ./ci/ci-compile.sh

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install platformio
        run: |
          pip install platformio==6.1.4

      - name: build examples
        run: ./ci/ci-compile.sh

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extra-args: -std=c++14 -Wall
          tidy-checks: -*,cert-*,clang-analyzer-*,cppcoreguidelines-*,google-*,hicpp-*,llvm-*,misc-*,modernize-*,performance-*,readability-*,zircon-*