on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
          chmod +x ./ci/ci-compile.sh

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install platformio
        run: |
          pip install platformio==6.1.4

      - name: build examples
        run: ./ci/ci-compile.sh