name: cpp-linter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extra-args: -std=c++14 -Wall
          tidy-checks: -*,cert-*,clang-analyzer-*,cppcoreguidelines-*,google-*,hicpp-*,llvm-*,misc-*,modernize-*,performance-*,readability-*,zircon-*

# TODO: Create own action for this.
#      - name: cppcheck
#        uses: deep5050/cppcheck-action@main
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN}}
#          platform: 'avr8'
#          other_options: '--enable=all --std=c++17 --suppress=*:*/.pio/* --suppress=*:*/lib/* --suppress=missingIncludeSystem --suppress=unmatchedSuppression --suppress=missingInclude --suppress=unusedFunction'

#      - name: publish report
#        uses: mikeal/publish-to-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH_NAME: 'main'

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1